"""LLM integration package for Glassbox."""

from glassbox.llm.adapters import (
    ModelAdapter,
    ModelAdapterStreamEvent,
    ModelFinalResult,
    ModelProviderConfig,
    ModelTextDelta,
    ModelToolCall,
    ModelToolCallDelta,
    PreparedModelTurn,
    PydanticAIModelAdapter,
    PydanticAIStreamTranslator,
)
from glassbox.llm.executor import (
    ModelExecutionResult,
    ModelExecutor,
    PydanticAIModelExecutor,
    build_anthropic_model_executor,
    build_local_text_model_executor,
    build_openai_model_executor,
)
from glassbox.llm.prompts import (
    build_approval_policy_prompt_fragment,
    build_artifact_backed_context_prompt_fragment,
    build_memory_notes_prompt_fragment,
    build_output_style_prompt_fragment,
    build_repo_context_prompt_fragment,
    build_runtime_prompt_fragment,
    build_system_prompt,
    build_tool_usage_prompt_fragment,
    build_working_set_prompt_fragment,
)

__all__ = [
    "ModelAdapter",
    "ModelAdapterStreamEvent",
    "ModelExecutionResult",
    "ModelExecutor",
    "ModelFinalResult",
    "ModelProviderConfig",
    "ModelTextDelta",
    "ModelToolCall",
    "ModelToolCallDelta",
    "PydanticAIModelExecutor",
    "PreparedModelTurn",
    "PydanticAIModelAdapter",
    "PydanticAIStreamTranslator",
    "build_approval_policy_prompt_fragment",
    "build_artifact_backed_context_prompt_fragment",
    "build_anthropic_model_executor",
    "build_local_text_model_executor",
    "build_memory_notes_prompt_fragment",
    "build_openai_model_executor",
    "build_output_style_prompt_fragment",
    "build_repo_context_prompt_fragment",
    "build_runtime_prompt_fragment",
    "build_system_prompt",
    "build_tool_usage_prompt_fragment",
    "build_working_set_prompt_fragment",
]
